workflows:
  flutter-workflow:
    name: Flutter Workflow
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      java: 17
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$FLUTTER_ROOT" > android/local.properties
      - name: Clean project
        script: |
          flutter clean
      - name: Enable Web Support and Get Packages
        script: |
          # تفعيل دعم الويب لتجنب انهيار مكتبات الجافا سكريبت
          flutter config --enable-web
          flutter pub get
      - name: Build Android APK
        script: |
          flutter build apk --release --no-pub
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
