workflows:
  flutter-workflow:
    name: Flutter Workflow
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: 3.22.3
      java: 17
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$FLUTTER_ROOT" > android/local.properties
      - name: Clean and Get Packages
        script: |
          flutter clean
          flutter pub get
      - name: Fix Kotlin and Build APK
        script: |
          # الانتقال لمجلد الأندرويد لتحديث الإعدادات وإصلاح الانهيار البرمجي
          cd android
          ./gradlew clean
          cd ..
          flutter build apk --debug --verbose
    artifacts:
      - build/app/outputs/flutter-apk/*.apk

